#!/bin/bash

# This shell script builds pdf2htmlEX

# source ./buildScripts/reSourceVersionEnvs
. ./buildScripts/reSourceVersionEnvs

echo ""
echo "-------------------------------------------------------------------"
echo "BUILDING pdf2htmlEX (using gcc)"
echo "  PDF2HTMLEX_VERSION = [$PDF2HTMLEX_VERSION]"
echo "-------------------------------------------------------------------"
echo "$1"
echo ""

set -ev

cd pdf2htmlEX


if [ "$1" = "clean" ] ; then
  rm -rf build
  mkdir build
fi

cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$PDF2HTMLEX_PREFIX ..
make $MAKE_PARALLEL
